### ISSUE TITLE
Add support for speech to text using whisper

### ISSUE THREAD

**Issue by nchapman** [nchapman/nebula#5]
Follow the same pattern we're using with llama.cpp to create an API around whisper.cpp. 

https://github.com/ggerganov/whisper.cpp

We should also support regular and [streaming](https://github.com/ggerganov/whisper.cpp/tree/master/examples/stream) APIs so that we can transcribe in real time.

**Comment by iKachaykin** [comment]
@nchapman first feedback: running it directly is very simple and straightforward, will experiment with Rust bindings now.

**Comment by iKachaykin** [comment]
Rust bindings for whisper also worked on my end without too big problems. They provide a regular usage for audio files examples. Stream example may be found here -> https://github.com/tazz4843/whisper-rs/pull/26/files (checkout: https://github.com/tazz4843/whisper-rs/blob/7878d45a860d257c2ed23fcc743f599d9276ccdd/examples/stream/src/main.rs), but it wasn't merged to main, so the code there may be a bit out of date and will need some adjustment.

I am right now going to start integrating this binding usage into API that Yurii created. Created a separate branch for that. I think it would make sense to make a quick call for me and Yurii next week, so that he may give me an overview of API that he has already implemented to make sure that the code that I develop is aligned with his one. @Warefoxe what do you think?

@nchapman do you see it the same way, or should I rather investigate some other things and Yurii will add this to API? What is your vision over that? :)

**Comment by nchapman** [comment]
Sorry I missed this! Yep, sounds good to me. I do wonder if we should use whisper.ccp directly rather than one of these wrappers so that we don't have to worry about which parts they support (like streaming). What do you think @iKachaykin>

**Comment by iKachaykin** [comment]
@nchapman No problem at all :)

As for using whisper.cpp directly, it is in theory possible. At the same time, it seems like we will end up re-implementing our own bindings that may be even more time consuming :thinking: 

After all it isn't that difficult to work with the bindings. I was a bit stuck with integrating that into API that Yurii implements though, but now it seems like I figured out the general idea. So I consider to finish with this task by tomorrow :)

**Comment by iKachaykin** [comment]
@nchapman should be completed right now. We will for sure discuss with Yurii tomorrow how to improve the current integration as it may need some refactoring. But overall whisper.cpp is already in nebula. Feel free to test it it on your end. To do so, you should run the following commands in terminal opened from nebula root:
1. `git fetch`
2. `git checkout 5-add-support-for-speech-to-text-using-whisper`
3. `git pull`
4. `mkdir models`
5. `wget -O models/ggml-base.en.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en.bin?download=true`
6. `cargo run --release --example whisper`

You are welcome to experiment with the model and with the audio sample file by setting them up in [whisper example file](https://github.com/nchapman/nebula/blob/5-add-support-for-speech-to-text-using-whisper/examples/whisper.rs).

**Comment by nchapman** [comment]
Looks great and works well for me! 👍

**Comment by iKachaykin** [comment]
@nchapman great, thanks for your feedback! Stream doesn't work that well at the same time. I integrated the code attached above, but it seems like it doesn't work after all. I will investigate that. Please let me know if you see other priorities for me at this point :)

**Comment by iKachaykin** [comment]
@nchapman A PR is ready to be merged from my point of view -> https://github.com/nchapman/nebula/pull/13, I put all the details there :) As we have no QA here, I close this issue for now. We may reopen it if at some point we realize that some extra job should be done, or we can open a new issue.
